# Generated by Django 3.2.3 on 2021-09-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('V', 'Vegetables'), ('G', 'Groceries'), ('D', 'Dairy')], max_length=2),
        ),
    ]
