# Generated by Django 3.2.3 on 2021-09-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'kg'), ('litre', 'litre'), ('.', '.')], max_length=7),
        ),
    ]
