# Generated by Django 3.2.7 on 2022-10-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('S', 'Shoes'), ('C', 'Crocs'), ('F', 'Flips')], max_length=2),
        ),
    ]
