# Generated by Django 3.2.7 on 2022-12-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_product_size_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='shoe_size',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
