# Generated by Django 3.2 on 2023-04-14 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='pro_quantity',
        ),
    ]
