# Generated by Django 3.2 on 2023-04-14 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_quantity_product_pro_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pro_quantity',
            new_name='quantity',
        ),
    ]
